; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = main
data_dir = spiffs_data


[env:esp32c3]
platform = espressif32
board = pico32
framework = espidf
monitor_speed = 115200
upload_speed = 921600
monitor_rts = 0
monitor_dtr = 0
board_build.flash_size = 4MB
board_build.flash_mode = dio
board_build.flash_freq = 40m
board_build.partitions = partitions_c3.csv
board_build.filesystem = spiffs
board_build.sdkconfig_defaults = sdkconfig.defaults sdkconfig.defaults.esp32c3
; build_flags = 
; 	-DCONFIG_ESP32_PICO=1
; 	-DCONFIG_SPIRAM_SUPPORT=0
; extra_scripts = post:scripts/pio_copy_bins.py
; lib_deps = 
; 	esp32async/ESPAsyncWebServer@^3.10.3
; 	esp32async/AsyncTCP@^3.4.10

[env:esp32pico]
platform = espressif32
board = pico32
framework = espidf
monitor_speed = 115200
upload_speed = 921600
monitor_rts = 0
monitor_dtr = 0
board_build.flash_size = 4MB
board_build.flash_mode = dio
board_build.flash_freq = 40m
board_build.partitions = partitions_pico.csv
board_build.filesystem = spiffs
board_build.sdkconfig_defaults = sdkconfig.defaults sdkconfig.defaults.esp32pico
; build_flags = 
	; -DCONFIG_ESP32_PICO=1
	; -DCONFIG_SPIRAM_SUPPORT=0
; extra_scripts = post:scripts/pio_copy_bins.py
; lib_deps = 
; 	esp32async/ESPAsyncWebServer@^3.10.3
; 	esp32async/AsyncTCP@^3.4.10